# Generated by Django 4.1 on 2022-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Info name')),
                ('about', models.TextField(verbose_name='Info text')),
                ('img', models.ImageField(upload_to='media', verbose_name='Info image')),
                ('date', models.DateField(verbose_name='Info date')),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
            },
        ),
    ]
